server:
  name: go-admin
  port: 8083
  secure: false
  key: "configs/key.pem"
  cert: "configs/cert.pem"
allow:
  origins: http://localhost:3000
  credentials: true
  methods: GET,PUT,POST,DELETE,OPTIONS,PATCH
  headers: Access-Control-Allow-Headers,Authorization,Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers
security_skip: false
template: true

log:
  level: info
  duration: duration
  fields: app,service,userId,username
  goroutines: true

middleware:
  log: true
  skips: /health,/authenticate
  request: request
  response: response
  masks: userId,username
  constants:
    app: "backoffice"
    service: back-office
  map:
    userId: userId
    username: username

ldap:
  tls: true
  insecure_skip_verify: true
  server: fake-ldap-server:389
  base_dn: dc=example,dc=com
  display_name: displayName
  users: test01,test02,kaka,zinedine.zidane,gareth.bale
  timeout: 3000
auth:
  token:
    secret: secretbackoffice
    expires: 86400000
  status:
    timeout: -1
    not_found: 0
    fail: 0
    success: 1
    password_expired: 3
    locked: 4
    suspended: 5
    disabled: 6
    error: 7
  payload:
    ip: ip
    id: userId
    username: username
    email: email
    lang: lang
  user_status:
    activated: A
    deactivated: I
    disable: D
    suspended: S
  query: |
    select u.user_id as id, u.username, u.display_name, email as contact, language, u.status, u.max_password_age, 
      p.password, p.success_time, p.fail_time, p.fail_count, p.locked_until_time, p.changed_time as passwordchangedtime
    from users u
    inner join passwords p
      on u.user_id = p.user_id
    where username = ?

db:
  driver: postgres
  data_source_name: postgres://postgres:abcd1234@localhost/cms?sslmode=disable

tracking:
  user: userId
  created_by: CreatedBy
  created_at: CreatedAt
  updated_by: UpdatedBy
  updated_at: UpdatedAt
action:
  load: load
  create: create
  update: update
  patch: patch
  delete: delete

code:
  handler:
    master: true
    id: value
    name: text
  loader:
    master: master
    id: code
    name: name
    sequence: sequence
    status: status
    active: A
role:
  handler:
    master: false
    id: roleId
    name: roleName
  loader:
    id: role_id
    name: role_name
    sequence: role_name
    status: status
    active: A

auto_role_id: false
auto_user_id: false

audit_log:
  log: true
  db:
    driver: postgres
    data_source_name: postgres://postgres:abcd1234@localhost/cms?sslmode=disable
  schema:
    id: id
    user: user_id
    ip: ip
    resource: resource
    action: action
    timestamp: time
    status: status
    desc: remark
  config:
    user: userId
    ip: ip
    true: success
    false: fail
    goroutines: true
