sql:
  privileges: |
    select module_id as id,
      module_name as name,
      resource_key,
      path,
      icon,
      parent,
      actions,
      sequence
    from modules
    where status = 'A'
  privileges_by_user: |
    select distinct m.module_id as id, m.module_name as name, m.resource_key,
      m.path, m.icon, m.parent, m.sequence, rm.permissions, m.actions
    from users u
      inner join user_roles ur on u.user_id = ur.user_id
      inner join roles r on ur.role_id = r.role_id
      inner join role_modules rm on r.role_id = rm.role_id
      inner join modules m on rm.module_id = m.module_id
    where u.user_id = ? and r.status = 'A' and m.status = 'A'
    order by sequence
  permissions_by_user: |
    select distinct rm.permissions
    from users u
      inner join user_roles ur on u.user_id = ur.user_id
      inner join roles r on ur.role_id = r.role_id
      inner join role_modules rm on r.role_id = rm.role_id
      inner join modules m on rm.module_id = m.module_id
    where u.user_id = ? and u.status = 'A' and r.status = 'A' and rm.module_id = ? and m.status = 'A'
  role:
    check: select user_id from user_roles where role_id = ? limit 1
